
// A comprehensive list of timezones with their offsets from UTC
export const timezones = [
  { value: "Pacific/Midway", label: "Midway Island, Samoa", offset: "UTC-11:00" },
  { value: "Pacific/Honolulu", label: "Hawaii", offset: "UTC-10:00" },
  { value: "America/Anchorage", label: "Alaska", offset: "UTC-09:00" },
  { value: "America/Los_Angeles", label: "Pacific Time (US & Canada)", offset: "UTC-08:00" },
  { value: "America/Phoenix", label: "Arizona", offset: "UTC-07:00" },
  { value: "America/Denver", label: "Mountain Time (US & Canada)", offset: "UTC-07:00" },
  { value: "America/Chicago", label: "Central Time (US & Canada)", offset: "UTC-06:00" },
  { value: "America/New_York", label: "Eastern Time (US & Canada)", offset: "UTC-05:00" },
  { value: "America/Toronto", label: "Toronto", offset: "UTC-05:00" },
  { value: "America/Halifax", label: "Atlantic Time (Canada)", offset: "UTC-04:00" },
  { value: "America/Caracas", label: "Caracas", offset: "UTC-04:00" },
  { value: "America/Sao_Paulo", label: "Sao Paulo", offset: "UTC-03:00" },
  { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires", offset: "UTC-03:00" },
  { value: "Atlantic/South_Georgia", label: "Mid-Atlantic", offset: "UTC-02:00" },
  { value: "Atlantic/Azores", label: "Azores", offset: "UTC-01:00" },
  { value: "Europe/London", label: "London, Dublin, Edinburgh", offset: "UTC+00:00" },
  { value: "Europe/Paris", label: "Paris, Madrid, Brussels", offset: "UTC+01:00" },
  { value: "Europe/Berlin", label: "Berlin, Rome, Amsterdam", offset: "UTC+01:00" },
  { value: "Europe/Athens", label: "Athens, Istanbul, Helsinki", offset: "UTC+02:00" },
  { value: "Asia/Jerusalem", label: "Jerusalem", offset: "UTC+02:00" },
  { value: "Asia/Riyadh", label: "Kuwait, Riyadh", offset: "UTC+03:00" },
  { value: "Asia/Moscow", label: "Moscow, St. Petersburg", offset: "UTC+03:00" },
  { value: "Asia/Dubai", label: "Abu Dhabi, Dubai", offset: "UTC+04:00" },
  { value: "Asia/Kabul", label: "Kabul", offset: "UTC+04:30" },
  { value: "Asia/Karachi", label: "Islamabad, Karachi", offset: "UTC+05:00" },
  { value: "Asia/Kolkata", label: "Mumbai, New Delhi", offset: "UTC+05:30" },
  { value: "Asia/Kathmandu", label: "Kathmandu", offset: "UTC+05:45" },
  { value: "Asia/Dhaka", label: "Dhaka", offset: "UTC+06:00" },
  { value: "Asia/Yangon", label: "Yangon", offset: "UTC+06:30" },
  { value: "Asia/Bangkok", label: "Bangkok, Jakarta", offset: "UTC+07:00" },
  { value: "Asia/Shanghai", label: "Beijing, Shanghai", offset: "UTC+08:00" },
  { value: "Asia/Singapore", label: "Singapore, Kuala Lumpur", offset: "UTC+08:00" },
  { value: "Asia/Tokyo", label: "Tokyo, Osaka", offset: "UTC+09:00" },
  { value: "Australia/Sydney", label: "Sydney, Melbourne", offset: "UTC+10:00" },
  { value: "Pacific/Noumea", label: "New Caledonia", offset: "UTC+11:00" },
  { value: "Pacific/Auckland", label: "Auckland, Wellington", offset: "UTC+12:00" },
  { value: "Pacific/Fiji", label: "Fiji Islands", offset: "UTC+12:00" },
  { value: "Pacific/Tongatapu", label: "Nuku'alofa", offset: "UTC+13:00" },
];
